### ISSUE TITLE
REQUEST_URL is malformed with parameters in a cold function

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#111]
In gitlab by @will_p on Jul 11, 2017, 06:10

The request url injected as an environment variable (`REQUEST_URL`) mutates the URL dropping the everything after the first `=` (doesn't appear to occur with hot functions)

```yaml
# file: func.yaml
name: willprice/fn-demo-env-vars
version: 0.0.4
runtime: go
entrypoint: ./
```

```go
// file: func.go
package main

import (
  "fmt"
  "os"
  "strings"
)

func main() {
    for _, e := range os.Environ() {
        pair := strings.Split(e, "=")
        fmt.Println(pair[0], pair[1])
    }
}
```

```
$ fn apps create env-vars
$ fn deploy env-vars
$ curl --noproxy '*' 'http://localhost:8080/r/env-vars/env-vars?paramx=45&var=4'
...
REQUEST_URL http//localhost:8080/r/env-vars/env-vars?paramx
...
