### ISSUE TITLE
fn run access to func+app configs

### ISSUE THREAD

**Issue by rdallman** [fnproject/fn#129]
In gitlab by @carimura on Jul 17, 2017, 17:57

does it make sense to have `fn run` get function configs? `fn run` is super nice for local development, but all funcs will almost inevitably use config secrets (ie db creds, etc.) which makes `run` unusable unless you write a script to set local env variables every time.... the alternative is to keep doing `fn deploy; fn call` but sorta defeats entire purpose. Would be great to just map the funcs config into the ENV beforehand? That said we'd also need the app config as well.....

ideally local development would have it's own set of dev creds for everything that the user controls, and prod is different, obviously.

**Comment by treeder** [comment]
This may already solve this: https://github.com/fnproject/cli/pull/20

Eg:

```yaml
version: 0.0.1
runtime: go
entrypoint: ./func
expects:
  config:
    - name: SECRET_1
      required: true
    - name: SECRET_2
```
