### ISSUE TITLE
Some help required running Fn on Kubernetes

### ISSUE THREAD

**Issue by fadams** [fnproject/fn#1459]
Hello all. I've been enjoying trying out Fn and things seem to be working pretty well for me running a simple server with `fn start` and even running my own server using docker run, so I'm good to go on simple use-cases. I've come a bit unstuck however trying to get Fn running on Kubernetes.

I'm aware that this is a distributed configuration involving several different fnproject/fnserver Node Types and have read up on that topology here https://medium.com/fnproject/distributed-fn-beyond-fn-start-2ee0baf6fb77 and here https://github.com/fnproject/docs/blob/master/fn/operate/production.md

I'm aware of the Fn helm chart https://github.com/fnproject/fn-helm and I'm using that as my starting point but to try and get my head around things a little my goal was to try and get things running using a simple NodePort service type to run on my local machine.

I'm running a very simple local docker registry using the registry:2 image on localhost:5000 and my setup is working fine with OpenFaaS, which I set up as a control to try and rule out any silly issues with my basic set-up.

I'll try to give some detail of exactly where I'm at as follows:

I created a deployment fn.yaml using the helm chart as a template e.g.
```
git clone https://github.com/fnproject/fn-helm.git
helm dep build fn-helm/fn
helm template --name fn --namespace fn fn-helm/fn > fn.yaml
```
to keep things tidy I created a fn namespace on my K8s cluster
```
kubectl create namespace fn
```
Next I edited the fn.yaml to include the fn namespace and add the NodePort stuff. The relevant parts are below, apart from adding the fn namespace I haven't changed the fn-mysql, fn-redis, fn-fn-flow or fn-fn-ui parts - I'm just focussing on the core function CRUD and invocation parts ATM so the ke parts are:
```
---
# Source: fn/templates/fn-runner-node-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fn-fn-runner
  namespace: "fn"
  labels:
    app: fn-fn
    chart: fn-0.1.0
    heritage: Tiller
    release: fn
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9191
      targetPort: 9191
  selector:
    app: fn-fn
    role: runner

---
# Source: fn/templates/fn-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fn-fn
  namespace: "fn"
  labels:
    app: fn-fn
    chart: fn-0.1.0
    heritage: Tiller
    release: fn
spec:
#  type: ClusterIP
  type: NodePort
  ports:
  - name: api
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: runner-lb
    port: 90
    targetPort: 90
    nodePort: 30090
  selector:
    app: fn-fn
    role: fn-service

---
---
# Source: fn/templates/fn-deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fn-fn
  namespace: "fn"
  labels:
    app: fn-fn
    chart: fn-0.1.0
    heritage: Tiller
    release: fn
spec:
  replicas: 1
  template:
    metadata:
       labels:
         app: fn-fn
         chart: fn-0.1.0
         heritage: Tiller
         release: fn
         role: fn-service
    spec:
      containers:
        - name: api
          image: fnproject/fnserver:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 2Gi
            requests:
              cpu: 150m
              memory: 512Mi
            
          securityContext:
            privileged: true
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /v2/apps
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
          - name: FN_DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: fn-mysql
                key: mysql-password
          - name: FN_DB_HOST
            value: fn-mysql
          - name: FN_MQ_HOST
            value: fn-redis
          - name: FN_PORT
            value: "80"
          - name: FN_NODE_TYPE
            value: "api"
          - name: FN_PUBLIC_LB_URL
#            value: http://fn.lb.fn.internal:90
            value: http://10.192.0.2:30090
          - name: FN_DB_URL
            value: "mysql://fnapp:$(FN_DB_PASSWD)@tcp($(FN_DB_HOST):3306)/fndb"
          - name: FN_LOG_LEVEL
            value: "INFO"
          - name: FN_MQ_URL
            value: "redis://$(FN_MQ_HOST):6379/"
        - name: runner-lb
          image: fnproject/fnserver:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 2Gi
            requests:
              cpu: 150m
              memory: 512Mi
            
          securityContext:
            privileged: true
          ports:
          - containerPort: 90
          env:
          - name: FN_NODE_TYPE
            value: "lb"
          - name: FN_GRPC_PORT
            value: "9191"
          - name: FN_PORT
            value: "90"
          - name: FN_RUNNER_API_URL
            value: http://fn-fn.fn.svc.cluster.local:80
          - name: FN_RUNNER_ADDRESSES
            value: fn-fn-runner.fn.svc.cluster.local:9191
          - name: FN_LOG_LEVEL
            value: "INFO"

---
# Source: fn/templates/fn-runner-node-deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fn-fn-runner
  namespace: "fn"
  labels:
    app: fn-fn
    chart: fn-0.1.0
    heritage: Tiller
    release: fn
spec:
  replicas: 3
  template:
    metadata:
       labels:
         app: fn-fn
         chart: fn-0.1.0
         heritage: Tiller
         release: fn
         role: runner
    spec:
      containers:
        - name: runner
          image: fnproject/fnserver:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 5Gi
            requests:
              cpu: 250m
              memory: 1Gi
            
          securityContext:
            privileged: true
          ports:
          - containerPort: 9191
          env:
          - name: FN_NODE_TYPE
            value: "pure-runner"
          - name: FN_GRPC_PORT
            value: "9191"
          - name: FN_LOG_LEVEL
            value: "INFO"
---
```
The relevent bits really are that in the fn-service I changed the type to NodePort and added nodePort: 30080 to api and nodePort: 30090 to runner-lb. The other change is that under fn-deployment I changed the FN_PUBLIC_LB_URL value from http://fn.lb.fn.internal:90 to http://10.192.0.2:30090

When I deploy this with
```
kubectl apply -f ./fn.yaml
```
I see a successful deployment in the Kubernetes dashboard.
I have set up my context to point to the required API URL and registry:
```
fn list contexts
CURRENT	NAME	PROVIDER	API URL			REGISTRY
*	default	default		http://10.192.0.2:30080	localhost:5000
```
and fn version is happy, correctly returning the server version:
```
fn version
Client version is latest version: 0.5.69
Server version:  0.3.687
```
As far as I can see it looks like my API is running fine and I seem to be able to correctly run the CRUD operations, my issue is with the fn invoke, which is clearly rather important :-)

I've tested using http://fnproject.io/tutorials/Introduction/ as follows:
```
fn init --runtime go --trigger http gofn
Creating function at: /gofn
Function boilerplate generated.
func.yaml created.
```
```
fn create app goapp
Successfully created app:  goapp
```
```
fn --verbose deploy --app goapp
Deploying gofn to app: goapp
Bumped to version 0.0.2
Building image localhost:5000/gofn:0.0.2 
FN_REGISTRY:  localhost:5000
Current Context:  default
Sending build context to Docker daemon   5.12kB
Step 1/10 : FROM fnproject/go:dev as build-stage
dev: Pulling from fnproject/go
cd784148e348: Pull complete 
7e273b0dfc44: Pull complete 
952c3806fd1a: Pull complete 
daee55ea059d: Pull complete 
18dd7cffb4bd: Pull complete 
02ef0ff2b601: Pull complete 
Digest: sha256:fad7d110064e144fe9de90c2199146d83e6f9fdd6d6129bba1e7c7b67b81f8a3
Status: Downloaded newer image for fnproject/go:dev
 ---> 96c8fb94a8e1
Step 2/10 : WORKDIR /function
 ---> Running in 10d0f4cbf78c
Removing intermediate container 10d0f4cbf78c
 ---> d6fe38e1aa4a
Step 3/10 : RUN go get -u github.com/golang/dep/cmd/dep
 ---> Running in 04d806267d73
Removing intermediate container 04d806267d73
 ---> a6b205de47e7
Step 4/10 : ADD . /go/src/func/
 ---> 48fd62a784e7
Step 5/10 : RUN cd /go/src/func/ && dep ensure
 ---> Running in 7e224f97c846
Removing intermediate container 7e224f97c846
 ---> 5c285fadec58
Step 6/10 : RUN cd /go/src/func/ && go build -o func
 ---> Running in 32ff032d1cdd
Removing intermediate container 32ff032d1cdd
 ---> 294a608d7833
Step 7/10 : FROM fnproject/go
latest: Pulling from fnproject/go
ba7f5deea89d: Pull complete 
a243235fe902: Pull complete 
Digest: sha256:d30b00a023590955fc450d109bf57a649f69f7403fec164912dc85ade4749dc8
Status: Downloaded newer image for fnproject/go:latest
 ---> d9de4156fe50
Step 8/10 : WORKDIR /function
 ---> Running in eac3b7cc6be0
Removing intermediate container eac3b7cc6be0
 ---> 31f13b455c60
Step 9/10 : COPY --from=build-stage /go/src/func/func /function/
 ---> 945549427c78
Step 10/10 : ENTRYPOINT ["./func"]
 ---> Running in 43bf9010a9bf
Removing intermediate container 43bf9010a9bf
 ---> 24969be1ac7a
Successfully built 24969be1ac7a
Successfully tagged localhost:5000/gofn:0.0.2

Parts:  [localhost:5000 gofn:0.0.2]
Pushing localhost:5000/gofn:0.0.2 to docker registry...The push refers to repository [localhost:5000/gofn]
27e712241c73: Pushed 
6009b4785a95: Pushed 
db794edf2401: Pushed 
0b32a561a108: Pushed 
0.0.2: digest: sha256:d438a665d0d227142d5066994a67a8a48c14b8689e742a3b319080a3deb15418 size: 1157
Updating function gofn using image localhost:5000/gofn:0.0.2...
Successfully created function: gofn with localhost:5000/gofn:0.0.2
Successfully created trigger: gofn
Trigger Endpoint: http://10.192.0.2:30090/t/goapp/gofn
```
As far as I can see this all looks good so far and the Trigger Endpoint port is what I think I'm expecting it to be given how I set up the fn-service NodePort

and if I check my local registry by browsing to
```
http://localhost:5000/v2/_catalog
```
I can see gofn.

however.........

If I now do
```
fn invoke goapp gofn
```
The call hangs for a while, before eventually returning with:
```
Error invoking function. status: 500 message: internal server error
```
Following the instructions in https://medium.com/fnproject/distributed-fn-beyond-fn-start-2ee0baf6fb77 I tried:
```
fn inspect fn goapp gofn
```
which returns:
```
{
	"annotations": {
		"fnproject.io/fn/invokeEndpoint": "http://10.192.0.2:30090/invoke/01D7M8KVR41BT061G0A0000002"
	},
	"app_id": "01D7M8GH271BT061G0A0000001",
	"created_at": "2019-04-04T13:29:07.588Z",
	"id": "01D7M8KVR41BT061G0A0000002",
	"idle_timeout": 30,
	"image": "localhost:5000/gofn:0.0.2",
	"memory": 128,
	"name": "gofn",
	"timeout": 30,
	"updated_at": "2019-04-04T13:29:07.588Z"
}
```
again the IP/port of the invokeEndpoint are what I think I was expecting.

If I do
```
curl http://10.192.0.2:30090
```
I see
```
{"goto":"https://github.com/fnproject/fn","hello":"world!"}
```
But I think that's the welcome from the base endpoint not the function 'cause the function has "Hello World" with capitals
```
curl http://10.192.0.2:30090/invoke/01D7M8KVR41BT061G0A0000002
```
yields
```
{"message":"Method not allowed: GET /invoke/01D7M8KVR41BT061G0A0000002"}
```
and
```
curl http://10.192.0.2:30090/t/goapp/gofn
```
which is the trigger endpoint hangs for a bit and returns
```
{"message":"internal server error"}
```

I'd really appreciate any thoughts on this, I appreciate that using NodePort isn't the recommended approach but as far as I can see it *should" be possible to make it work OK and much of what I'm seeing looks like I'm expecting (apart from the invoke not working of course :-D). As I mentioned previously I got OpenFaaS working on the same set up so I think the underlying  infrastructure is basically sound.

MTIA
