### ISSUE TITLE
"No Consumer text/html"

### ISSUE THREAD

**Issue by ilovenuclearpower** [fnproject/fn#1575]
**Description**

When trying to deploy to a remote cluster (Amazon EKS), after setting up ingress and typing "fn-list-apps" I get an Fn:error no consumer "text/html" for every possible api call (fn list apps, fn deploy, etc).

**Steps to reproduce the issue:**
1. Deploy a k8s cluster with Amazon EKS
2. Set up kubectl access for your cluster from localhost (aws eks --region region --update-kubeconfig clustername
3. Deploy nginx-ingress controller on your kube cluster.
4. Deploy fn with ingress enabled.
5. Follow the guide in NOTES.txt of the project.

**Describe the results you received:**
```
ec2-user:~/environment/first-fn $ kubectl get svc
NAME                                       TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)                      AGE
api-testing-fn                             LoadBalancer   10.100.61.59     a1edaa292667611ea830502dba72cd3a-696535273.us-east-2.elb.amazonaws.com    80:30398/TCP,90:31932/TCP    12h
api-testing-fn-flow                        ClusterIP      10.100.173.196   <none>                                                                    80/TCP                       12h
api-testing-fn-runner                      ClusterIP      10.100.4.1       <none>                                                                    9191/TCP                     12h
api-testing-fn-ui                          LoadBalancer   10.100.91.88     a1ed61375667611ea830502dba72cd3a-1397700739.us-east-2.elb.amazonaws.com   3000:31415/TCP               12h
api-testing-mysql                          ClusterIP      10.100.15.183    <none>                                                                    3306/TCP                     12h
api-testing-redis                          ClusterIP      10.100.103.140   <none>                                                                    6379/TCP                     12h
controller-nginx-ingress-controller        LoadBalancer   10.100.123.237   ad646324d666d11ea8c930a53ab4d97e-1231034684.us-east-2.elb.amazonaws.com   80:31559/TCP,443:31026/TCP   13h
controller-nginx-ingress-default-backend   ClusterIP      10.100.31.177    <none>                                                                    80/TCP                       13h
kubernetes                                 ClusterIP      10.100.0.1       <none>                                                                    443/TCP                      6d9h
ec2-user:~/environment/first-fn $ echo ${HTTP_PROXY}

ec2-user:~/environment/first-fn $ export HTTP_PROXY=10.100.123.237
ec2-user:~/environment/first-fn $ fn use context api-testing-fn-3

Fn: Context api-testing-fn-3 currently in use

See 'fn <command> --help' for more information. Client version: 0.5.93
ec2-user:~/environment/first-fn $ fn list apps

Fn: Get http://api-testing.api.fn.internal:80/v2/apps: proxyconnect tcp: dial tcp 10.100.123.237:80: i/o timeout

See 'fn <command> --help' for more information. Client version: 0.5.93
ec2-user:~/environment/first-fn $ export HTTPS_PROXY=10.100.123.127
ec2-user:~/environment/first-fn $ fn list apps

Fn: Get http://api-testing.api.fn.internal:80/v2/apps: proxyconnect tcp: dial tcp 10.100.123.237:80: i/o timeout

See 'fn <command> --help' for more information. Client version: 0.5.93
ec2-user:~/environment/first-fn $ export HTTP_PROXY=ad646324d666d11ea8c930a53ab4d97e-1231034684.us-east-2.elb.amazonaws.com
ec2-user:~/environment/first-fn $ export HTTPS_PROXY=ad646324d666d11ea8c930a53ab4d97e-1231034684.us-east-2.elb.amazonaws.com
ec2-user:~/environment/first-fn $ fn list apps

Fn: no consumer: "text/html"

See 'fn <command> --help' for more information. Client version: 0.5.93
ec2-user:~/environment/first-fn $ 
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `fn version` (CLI command):**
```
Client version: 0.5.93
Server version:  ?

**Additional environment details (OSX, Linux, flags, etc.):**

Using Amazon EC2 on AL2 w/ AWS Cloud9
kubeconfig
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: SNIP
  name: arn:aws:eks:us-east-2:062568520934:cluster/fn-app-test-2
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:062568520934:cluster/fn-app-test-2
    user: arn:aws:eks:us-east-2:062568520934:cluster/fn-app-test-2
  name: arn:aws:eks:us-east-2:062568520934:cluster/fn-app-test-2
current-context: arn:aws:eks:us-east-2:062568520934:cluster/fn-app-test-2
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:062568520934:cluster/fn-app-test-2
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
       - "token"
       - "-i"
       - "fn-app-test-2"
      env:
       - name: AWS_PROFILE
         value: "default"
      command: aws-iam-authenticator
```
