### ISSUE TITLE
Multiple deploys cause headers specified in func.yaml to "add up"

### ISSUE THREAD

**Issue by edburns** [fnproject/fn#346]
Consider this func.yaml
```yaml
name: alert-manager
version: 0.0.46
runtime: java
cmd: com.oracle.state.demo::handleRequest
timeout: 1000
path: /alert-manager
headers:
  Access-Control-Allow-Headers: ['Authorization, Origin, X-Requested-With, Content-Type, Accept']
  Access-Control-Allow-Methods: ['POST, GET, OPTIONS']
  Access-Control-Allow-Origin: ['*']
  Content-type: ['text/json']
idle_timeout: 180
```

If I deploy this function several times in succession, I observe that when making an OPTIONS request to the service, the values of the response headers as specified above will be duplicated a number of times equal the number of deploys.
