### ISSUE TITLE
[Idea] Data schema validation during function's call

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fn#739]
Problem description
--------------------
At this particular moment, Fn doesn't really care about the data being sent through to the function.
So, all the request data processing is handled by the function. The downside is that Fn does a lot of things to spin up the function that would just fail if the data schema is bad for some reason.

Idea
----
Let developers define data schema through the API, for instance:
 - the function accepts plaintext:
```yaml
schema:
    type: object
    properties:
      body:
        type: string
        description: "plaintext body as a string"
```
 - the function accepts complex structure:
```yaml
schema:
    type: object
    properties:
      some_attr:
        type: string
        description: description
      int_val:
        type: integer
        format: uint64
        description: int val
      config:
        type: object
        description: serialized object
        additionalProperties:
          type: string
```

This type of data schema was taken from Swagger/Open API spec which makes it look familiar and simple enough to understand what data suppose to consist.
